#!/bin/bash
# Simple Password Generator

echo "This is a simple password generator"
echo "Please enter the length of the password:"
read PASS_LENGTH


#to get more password generated at a time change 
#for example 5 at a time $(seq 1 5)
for p in $(seq 1); do
	openssl rand -base64 48 | cut -c1-"$PASS_LENGTH"
done
